VISIT_OPTION_DEFAULT(VISIT_PARALLEL ON)
## (configured w/ mpi compiler wrapper)
VISIT_OPTION_DEFAULT(VISIT_MPI_COMPILER /usr/bin/mpic++)
SET(VISIT_MPI_CXX_FLAGS -I/usr/include/openmpi-x86_64)
SET(VISIT_MPI_LD_FLAGS -L/usr/lib64/openmpi/lib)
SET(VISIT_MPI_LIBS mpi_cxx mpi)
